-- SAA 2025 Mock Project — canonical Supabase schema
--
-- Scope agreed for this mock project:
--   - Exactly 4 application tables:
--       1. profiles
--       2. kudos
--       3. kudos_likes
--       4. gift_logs
--   - Google Auth via Supabase Auth
--   - Kudos images stored in Supabase Storage (`kudos-images` bucket)
--   - Homepage / Awards / i18n / countdown config / Spotlight content stay
--     in source code, not in DB
--
-- This file intentionally matches
-- `supabase/migrations/20260709_000001_init_saa_2025_mock_project.sql`.

begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  avatar_url text,
  department text
);

create table if not exists public.kudos (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles (id) on delete cascade,
  receiver_id uuid not null references public.profiles (id) on delete cascade,
  title text,
  content text not null,
  image_urls text[] not null default '{}',
  is_anonymous boolean not null default false,
  anonymous_name text,
  hashtags text[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint kudos_image_urls_max_5 check (coalesce(array_length(image_urls, 1), 0) <= 5)
);

create table if not exists public.kudos_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  kudos_id uuid not null references public.kudos (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint kudos_likes_user_id_kudos_id_key unique (user_id, kudos_id)
);

create table if not exists public.gift_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  gift_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists profiles_department_idx
  on public.profiles (department);

create index if not exists kudos_created_at_idx
  on public.kudos (created_at desc);

create index if not exists kudos_sender_id_idx
  on public.kudos (sender_id);

create index if not exists kudos_receiver_id_idx
  on public.kudos (receiver_id);

create index if not exists kudos_hashtags_gin_idx
  on public.kudos using gin (hashtags);

create index if not exists kudos_likes_kudos_id_idx
  on public.kudos_likes (kudos_id);

create index if not exists kudos_likes_user_id_idx
  on public.kudos_likes (user_id);

create index if not exists gift_logs_created_at_idx
  on public.gift_logs (created_at desc);

create index if not exists gift_logs_user_id_idx
  on public.gift_logs (user_id);

grant usage on schema public to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.kudos to authenticated;
grant select, insert, delete on public.kudos_likes to authenticated;
grant select, insert on public.gift_logs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles enable row level security;
alter table public.kudos enable row level security;
alter table public.kudos_likes enable row level security;
alter table public.gift_logs enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
  on public.profiles
  for select
  to authenticated
  using (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "kudos_select_authenticated" on public.kudos;
create policy "kudos_select_authenticated"
  on public.kudos
  for select
  to authenticated
  using (true);

drop policy if exists "kudos_insert_own" on public.kudos;
create policy "kudos_insert_own"
  on public.kudos
  for insert
  to authenticated
  with check ((select auth.uid()) = sender_id);

drop policy if exists "kudos_delete_own" on public.kudos;
create policy "kudos_delete_own"
  on public.kudos
  for delete
  to authenticated
  using ((select auth.uid()) = sender_id);

drop policy if exists "kudos_likes_select_authenticated" on public.kudos_likes;
create policy "kudos_likes_select_authenticated"
  on public.kudos_likes
  for select
  to authenticated
  using (true);

drop policy if exists "kudos_likes_insert_own" on public.kudos_likes;
create policy "kudos_likes_insert_own"
  on public.kudos_likes
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "kudos_likes_delete_own" on public.kudos_likes;
create policy "kudos_likes_delete_own"
  on public.kudos_likes
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "gift_logs_select_authenticated" on public.gift_logs;
create policy "gift_logs_select_authenticated"
  on public.gift_logs
  for select
  to authenticated
  using (true);

drop policy if exists "gift_logs_insert_own" on public.gift_logs;
create policy "gift_logs_insert_own"
  on public.gift_logs
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture')
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url;

  return new;
exception
  when others then
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('kudos-images', 'kudos-images', true)
on conflict (id) do nothing;

drop policy if exists "kudos_images_public_read" on storage.objects;
create policy "kudos_images_public_read"
  on storage.objects
  for select
  to public
  using (bucket_id = 'kudos-images');

drop policy if exists "kudos_images_insert_own_folder" on storage.objects;
create policy "kudos_images_insert_own_folder"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "kudos_images_update_own_folder" on storage.objects;
create policy "kudos_images_update_own_folder"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "kudos_images_delete_own_folder" on storage.objects;
create policy "kudos_images_delete_own_folder"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

commit;
