import { describe, it, expect, vi } from "vitest";
import type { ReactElement } from "react";

vi.mock("next/font/google", () => ({
  Montserrat: vi.fn(() => ({
    variable: "--font-montserrat",
    className: "font-montserrat",
  })),
  Montserrat_Alternates: vi.fn(() => ({
    variable: "--font-montserrat-alternates",
    className: "font-montserrat-alternates",
  })),
}));

vi.mock("next/font/local", () => ({
  default: vi.fn(() => ({ className: "font-digital-numbers" })),
}));

vi.mock("@/lib/i18n/get-locale", () => ({
  getLocale: vi.fn(async () => "vi"),
}));

import RootLayout, { metadata } from "./layout";

/**
 * `RootLayout` returns `<html>`/`<body>` directly, which jsdom refuses to
 * mount inside `render()`'s container `<div>` ("cannot be a child of
 * <div>"). Inspecting the returned React element's props directly sidesteps
 * that DOM-nesting restriction while still asserting exactly what would be
 * rendered onto `<html>`.
 */
async function renderLayout() {
  const element = (await RootLayout({
    children: null,
  })) as ReactElement<{ className?: string; lang?: string }>;
  return element.props;
}

describe("RootLayout", () => {
  it("applies the Montserrat + Montserrat Alternates variables on <html> (FR-F1)", async () => {
    const { className } = await renderLayout();

    // fonts.ts exports custom objects with Tailwind class names (not CSS custom properties):
    // montserrat.variable = "font-montserrat-variable"
    // montserratAlternates.variable = "font-montserrat-alternates-variable"
    expect(className).toContain("font-montserrat-variable");
    expect(className).toContain("font-montserrat-alternates-variable");
  });

  it("does not carry any Geist font variable (FR-F4)", async () => {
    const { className } = await renderLayout();

    expect(className).not.toMatch(/geist/i);
  });

  it("resolves <html lang> from getLocale()", async () => {
    const { lang } = await renderLayout();

    expect(lang).toBe("vi");
  });

  it("sets the real brand metadata title, not the create-next-app default (FR-F3)", () => {
    expect(metadata.title).toBe("Sun* Annual Awards 2025");
    expect(metadata.title).not.toBe("Create Next App");
    expect(metadata.description).not.toBe("Generated by create next app");
  });
});
