-- SAA 2025 Mock Project — initial Supabase schema
-- Scope:
--   - 4 core tables only: profiles, kudos, kudos_likes, gift_logs
--   - basic RLS for authenticated app usage
--   - profile auto-sync from Supabase Auth (Google OAuth)
--   - storage bucket + policies for Kudos image upload
--
-- Safe to run on a fresh project. For an existing project, review policy /
-- bucket names first to avoid conflicts with prior prototypes.

begin;

-- =============================================================================
-- Extensions
-- =============================================================================

create extension if not exists pgcrypto;

-- =============================================================================
-- Tables
-- =============================================================================

-- profiles: 1:1 app-level profile mirror of auth.users.
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  avatar_url text,
  department text
);

-- kudos: the core "thank you" post.
create table if not exists public.kudos (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles (id) on delete cascade,
  receiver_id uuid not null references public.profiles (id) on delete cascade,
  title text,
  content text not null,
  image_urls text[] not null default '{}',
  is_anonymous boolean not null default false,
  anonymous_name text,
  hashtags text[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint kudos_image_urls_max_5 check (coalesce(array_length(image_urls, 1), 0) <= 5)
);

-- kudos_likes: one row = one user's like on one kudos.
create table if not exists public.kudos_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  kudos_id uuid not null references public.kudos (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint kudos_likes_user_id_kudos_id_key unique (user_id, kudos_id)
);

-- gift_logs: minimal persistence for Secret Box / latest gifts.
create table if not exists public.gift_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  gift_name text not null,
  created_at timestamptz not null default now()
);

-- =============================================================================
-- Indexes
-- =============================================================================

create index if not exists profiles_department_idx
  on public.profiles (department);

create index if not exists kudos_created_at_idx
  on public.kudos (created_at desc);

create index if not exists kudos_sender_id_idx
  on public.kudos (sender_id);

create index if not exists kudos_receiver_id_idx
  on public.kudos (receiver_id);

create index if not exists kudos_hashtags_gin_idx
  on public.kudos using gin (hashtags);

create index if not exists kudos_likes_kudos_id_idx
  on public.kudos_likes (kudos_id);

create index if not exists kudos_likes_user_id_idx
  on public.kudos_likes (user_id);

create index if not exists gift_logs_created_at_idx
  on public.gift_logs (created_at desc);

create index if not exists gift_logs_user_id_idx
  on public.gift_logs (user_id);

-- =============================================================================
-- Grants
-- =============================================================================

grant usage on schema public to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.kudos to authenticated;
grant select, insert, delete on public.kudos_likes to authenticated;
grant select, insert on public.gift_logs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- =============================================================================
-- Row Level Security
-- =============================================================================

alter table public.profiles enable row level security;
alter table public.kudos enable row level security;
alter table public.kudos_likes enable row level security;
alter table public.gift_logs enable row level security;

-- profiles
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
  on public.profiles
  for select
  to authenticated
  using (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- kudos
drop policy if exists "kudos_select_authenticated" on public.kudos;
create policy "kudos_select_authenticated"
  on public.kudos
  for select
  to authenticated
  using (true);

drop policy if exists "kudos_insert_own" on public.kudos;
create policy "kudos_insert_own"
  on public.kudos
  for insert
  to authenticated
  with check ((select auth.uid()) = sender_id);

-- optional but practical: allow sender to delete their own post if UI adds it later
drop policy if exists "kudos_delete_own" on public.kudos;
create policy "kudos_delete_own"
  on public.kudos
  for delete
  to authenticated
  using ((select auth.uid()) = sender_id);

-- kudos_likes
drop policy if exists "kudos_likes_select_authenticated" on public.kudos_likes;
create policy "kudos_likes_select_authenticated"
  on public.kudos_likes
  for select
  to authenticated
  using (true);

drop policy if exists "kudos_likes_insert_own" on public.kudos_likes;
create policy "kudos_likes_insert_own"
  on public.kudos_likes
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "kudos_likes_delete_own" on public.kudos_likes;
create policy "kudos_likes_delete_own"
  on public.kudos_likes
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- gift_logs
drop policy if exists "gift_logs_select_authenticated" on public.gift_logs;
create policy "gift_logs_select_authenticated"
  on public.gift_logs
  for select
  to authenticated
  using (true);

drop policy if exists "gift_logs_insert_own" on public.gift_logs;
create policy "gift_logs_insert_own"
  on public.gift_logs
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- =============================================================================
-- Auth -> profile sync
-- =============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture')
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url;

  return new;
exception
  when others then
    -- Never block Google login if profile sync has a bad payload.
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- If a user already exists before this migration is applied, this helper can
-- be run manually once after deployment:
--
-- insert into public.profiles (id, full_name, avatar_url)
-- select
--   id,
--   coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name'),
--   coalesce(raw_user_meta_data ->> 'avatar_url', raw_user_meta_data ->> 'picture')
-- from auth.users
-- on conflict (id) do nothing;

-- =============================================================================
-- Storage for Kudos images
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('kudos-images', 'kudos-images', true)
on conflict (id) do nothing;

drop policy if exists "kudos_images_public_read" on storage.objects;
create policy "kudos_images_public_read"
  on storage.objects
  for select
  to public
  using (bucket_id = 'kudos-images');

drop policy if exists "kudos_images_insert_own_folder" on storage.objects;
create policy "kudos_images_insert_own_folder"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "kudos_images_update_own_folder" on storage.objects;
create policy "kudos_images_update_own_folder"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "kudos_images_delete_own_folder" on storage.objects;
create policy "kudos_images_delete_own_folder"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'kudos-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

commit;
